[package]
name = "hnsw"
version = "0.12.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2024"
description = "Fast approximate nearest neighbors"
keywords = ["hamming", "distance", "nearest", "neighbor", "search"]
categories = ["algorithms", "data-structures", "science"]
repository = "https://github.com/rust-cv/hnsw"
documentation = "https://docs.rs/hnsw/"
license = "MIT"
readme = "README.md"

[features]
serde1 = ["smallvec/serde", "serde"]

[[bench]]
name = "benches"
harness = false

[dependencies]
space = "0.19.0"
rand_core = "0.9.3"
hashbrown = "0.15.4"
serde = { version = "1.0.219", default-features = false, features = [
    "derive",
], optional = true }
libm = "0.2.15"
smallvec = { version = "1.15.1", features = ["const_generics"] }
ahash = { version = "0.8.12", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
pgat = "0.3.0"

[dev-dependencies]
rand_chacha = { version = "0.9.0", features = ["serde"] }
hamming-heap = "0.4.1"
rand = "0.9.2"
criterion = "0.7.0"
gnuplot = "0.0.46"
structopt = "0.3.26"
easybench = "1.1.1"
itertools = "0.14.0"
float-ord = "0.3.2"
byteorder = "1.5.0"
serde_json = "1.0.142"
num-traits = "0.2.19"
bitarray = { version = "0.10.0", default-features = false, features = [
    "space",
] }

[profile.dev]
opt-level = 3

[profile.test]
# The tests take a very long time without optimization.
opt-level = 3

[profile.release]
codegen-units = 1
# This is here so we can generate flamegraphs.
debug = true

[package.metadata.docs.rs]
all-features = true
